<?php 
// --------------------------------------------------------------------
// CLASS OBJECT/TEST CLASS FOR TABLE project
// Generated by Classmaker.php 
// Created by Adhadi Mohd
// 2011 (C) All Rights Reserved
// --------------------------------------------------------------------

/* Begin Class */

class cproject
{
 	var $id;
var $ProjectName;
var $Database;
var $ApplicationTemplate;


	function set_id($val) 
{ 
	$this->id = $val;  
}

function get_id() 
{
	return $this->id;
}

function set_ProjectName($val) 
{ 
	$this->ProjectName = $val;  
}

function get_ProjectName() 
{
	return $this->ProjectName;
}

function set_Database($val) 
{ 
	$this->Database = $val;  
}

function get_Database() 
{
	return $this->Database;
}

function set_ApplicationTemplate($val) 
{ 
	$this->ApplicationTemplate = $val;  
}

function get_ApplicationTemplate() 
{
	return $this->ApplicationTemplate;
}



	function insert()
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "INSERT INTO project (ProjectName,DatabaseName, ApplicationTemplate) VALUES ('$this->ProjectName','$this->Database','$this->ApplicationTemplate')";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
			$this->id = $mysqli->insert_id;
			
			return true;
		} else { 
		
			echo $mysqli->error;
		
		return false;}
	
		/* close connection */
		$mysqli->close();
	
	}
	
	
function delete($id)
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "DELETE FROM project WHERE id = $id";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
		
			return true;
	
		} else { return false;}
	
		/* close connection */
		$mysqli->close();
	
	}
	
	
function update($id)
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "UPDATE project SET ProjectName = '$this->ProjectName', Database = '$this->Database', ApplicationTemplate = '$this->ApplicationTemplate' WHERE id = $id";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
		
			return true;
	
		} else { return false;}
	
		/* close connection */
		$mysqli->close();
	
	}





function load($id)
{
	$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, "radtools");
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "SELECT * FROM project where id=$id";
		
		$result = $mysqli->query($query);
		$row = $result->fetch_assoc();
		//echo $row['id'];
		
		$this->id=$row['id'];
	$this->ProjectName=$row['ProjectName'];
	$this->Database=$row['DatabaseName'];
	$this->ApplicationTemplate=$row['ApplicationTemplate'];

	
	}}

/* End Class */





// ---------------------------------------------------------------
//  CODE FOR TESTING
// ---------------------------------------------------------------
class cprojectTest

{
	
	function testInsert($ProjectName,$Database,$ApplicationTemplate) 
	
	{
		$oproject= new cproject();
	
	$oproject->set_id($id);
$oproject->set_ProjectName($ProjectName);
$oproject->set_Database($Database);
$oproject->set_ApplicationTemplate($ApplicationTemplate);

	
	$oproject->insert();
	return $oproject->get_id();
	}
	
	function testUpdate($id,$ProjectName,$Database,$ApplicationTemplate) 
	
	{
		$oproject= new cproject();
	
	$oproject->set_id($id);
$oproject->set_ProjectName($ProjectName);
$oproject->set_Database($Database);
$oproject->set_ApplicationTemplate($ApplicationTemplate);

	
	
	$ret= $oproject->update($id);
	
	if ($ret>0)
		{
		return $ret;
		} else {
		return false;
		}
	}
	
	
	
	function getrandstring()
	{
		$n = rand(10e16, 10e20);
		return base_convert($n, 10, 36);
	}
	
	
	// --------------------------------------------------------------
	function testLoad($id)
	{
	
	$oproject= new cproject();
	$oproject->load($id);
	
	echo $oproject->id."<br>";
echo $oproject->ProjectName."<br>";
echo $oproject->Database."<br>";
echo $oproject->ApplicationTemplate."<br>";

	
	}
	
	
	
	// --------------------------------------------------------------
	function testDelete($id)
	{
	
	$oproject= new cproject();
	$ret = $oproject->delete($id);
	
	if ($ret)
	{ echo "Delete Success"; }
	else
	{ echo "Delete Failed"; }
	
	}
	
	// ------------------ Begin Testing ------------------------------
	function BeginTest()
	{
	
	echo "<h2>Begin Test</h2>";
	$ProjectName= getrandstring();
$Database= getrandstring();
$ApplicationTemplate= getrandstring();

	
	
	$retVal = $this->testInsert($ProjectName,$Database,$ApplicationTemplate);
	
	echo "<h4>Test Insert</h4>";
	if ($retVal>0)
	{ 
	echo "Test Insert [SUCCESS] with ID Value $retVal <br>";
	} else
	echo "Test Insert [Failed]  <br>";
	
	echo "<h4>Test Load</h4>";
	$this->testLoad($retVal);
	
	
	echo "<h4>Test Update</h4>";
	$ProjectName= getrandstring();
$Database= getrandstring();
$ApplicationTemplate= getrandstring();

	$this->testUpdate($retVal,$ProjectName,$Database,$ApplicationTemplate );
	
	echo "<h4>Test Load After Update</h4>";
	$this->testLoad($retVal);
	
	echo "<h4>Test Delete</h4>";
	$this->testDelete($retVal);
	}
}




?>