<?php 
// --------------------------------------------------------------------
// CLASS OBJECT/TEST CLASS FOR TABLE projecttables
// Generated by Classmaker.php 
// Created by Adhadi Mohd
// 2011 (C) All Rights Reserved
// --------------------------------------------------------------------


/* Begin Class */

class cprojecttables
{
 	var $id;
var $project_id;
var $TableName;
var $TableAlias;
var $Description;
var $Process;


	function set_id($val) 
{ 
	$this->id = $val;  
}

function get_id() 
{
	return $this->id;
}

function set_project_id($val) 
{ 
	$this->project_id = $val;  
}

function get_project_id() 
{
	return $this->project_id;
}

function set_TableName($val) 
{ 
	$this->TableName = $val;  
}

function get_TableName() 
{
	return $this->TableName;
}

function set_TableAlias($val) 
{ 
	$this->TableAlias = $val;  
}

function get_TableAlias() 
{
	return $this->TableAlias;
}

function set_Description($val) 
{ 
	$this->Description = $val;  
}

function get_Description() 
{
	return $this->Description;
}

function set_Process($val) 
{ 
	$this->Process = $val;  
}

function get_Process() 
{
	return $this->Process;
}



	function insert()
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "INSERT INTO projecttables (project_id,TableName,TableAlias,Description,Process) VALUES ($this->project_id,'$this->TableName','$this->TableAlias','$this->Description',$this->Process)";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
			$this->id = $mysqli->insert_id;
			
			return true;
		} else { return false;}
	
		/* close connection */
		$mysqli->close();
	
	}
	
	
function delete($id)
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "DELETE FROM projecttables WHERE id = $id";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
		
			return true;
	
		} else { return false;}
	
		/* close connection */
		$mysqli->close();
	
	}
	
	
function update($id)
	{
		$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "UPDATE projecttables SET project_id = $this->project_id, TableName = '$this->TableName', TableAlias = '$this->TableAlias', Description = '$this->Description', Process = $this->Process WHERE id = $id";
		
		//echo $query;
		
		if ($mysqli->query($query)) {
			
		
			return true;
	
		} else { return false;}
	
		/* close connection */
		$mysqli->close();
	
	}





function load($id)
{
	$mysqli = new mysqli( DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
		/* check connection */
	
		if (mysqli_connect_errno()) {
			printf("Connect failed: %s\n", mysqli_connect_error());
			exit();
		}
		
		$query= "SELECT * FROM projecttables where id=$id";
		//echo $query;
		$result = $mysqli->query($query);
		$row = $result->fetch_assoc();
		//echo $row['id'];
		
			$this->id=$row['id'];
	$this->project_id=$row['project_id'];
	$this->TableName=$row['TableName'];
	$this->TableAlias=$row['TableAlias'];
	$this->Description=$row['Description'];
	$this->Process=$row['Process'];

	
	}}

/* End Class */





// ---------------------------------------------------------------
//  CODE FOR TESTING
// ---------------------------------------------------------------
class cprojecttablesTest

{
	
	function testInsert($project_id,$TableName,$TableAlias,$Description,$Process) 
	
	{
		$oprojecttables= new cprojecttables();
	
	$oprojecttables->set_id($id);
$oprojecttables->set_project_id($project_id);
$oprojecttables->set_TableName($TableName);
$oprojecttables->set_TableAlias($TableAlias);
$oprojecttables->set_Description($Description);
$oprojecttables->set_Process($Process);

	
	$oprojecttables->insert();
	return $oprojecttables->get_id();
	}
	
	function testUpdate($id,$project_id,$TableName,$TableAlias,$Description,$Process) 
	
	{
		$oprojecttables= new cprojecttables();
	
	$oprojecttables->set_id($id);
$oprojecttables->set_project_id($project_id);
$oprojecttables->set_TableName($TableName);
$oprojecttables->set_TableAlias($TableAlias);
$oprojecttables->set_Description($Description);
$oprojecttables->set_Process($Process);

	
	
	$ret= $oprojecttables->update($id);
	
	if ($ret>0)
		{
		return $ret;
		} else {
		return false;
		}
	}
	
	
	
	function getrandstring()
	{
		$n = rand(10e16, 10e20);
		return base_convert($n, 10, 36);
	}
	
	
	// --------------------------------------------------------------
	function testLoad($id)
	{
	
	$oprojecttables= new cprojecttables();
	$oprojecttables->load($id);
	
	echo $oprojecttables->id."<br>";
echo $oprojecttables->project_id."<br>";
echo $oprojecttables->TableName."<br>";
echo $oprojecttables->TableAlias."<br>";
echo $oprojecttables->Description."<br>";
echo $oprojecttables->Process."<br>";

	
	}
	
	
	
	// --------------------------------------------------------------
	function testDelete($id)
	{
	
	$oprojecttables= new cprojecttables();
	$ret = $oprojecttables->delete($id);
	
	if ($ret)
	{ echo "Delete Success"; }
	else
	{ echo "Delete Failed"; }
	
	}
	
	// ------------------ Begin Testing ------------------------------
	function BeginTest()
	{
	
	echo "<h2>Begin Test</h2>";
	$project_id= rand();
$TableName= getrandstring();
$TableAlias= getrandstring();
$Description= getrandstring();
$Process= rand();

	
	
	$retVal = $this->testInsert($project_id,$TableName,$TableAlias,$Description,$Process);
	
	echo "<h4>Test Insert</h4>";
	if ($retVal>0)
	{ 
	echo "Test Insert [SUCCESS] with ID Value $retVal <br>";
	} else
	echo "Test Insert [Failed]  <br>";
	
	echo "<h4>Test Load</h4>";
	$this->testLoad($retVal);
	
	
	echo "<h4>Test Update</h4>";
	$project_id= rand();
$TableName= getrandstring();
$TableAlias= getrandstring();
$Description= getrandstring();
$Process= rand();

	$this->testUpdate($retVal,$project_id,$TableName,$TableAlias,$Description,$Process );
	
	echo "<h4>Test Load After Update</h4>";
	$this->testLoad($retVal);
	
	echo "<h4>Test Delete</h4>";
	$this->testDelete($retVal);
	}
}




?>